language: android

jdk:
 - oraclejdk7

before_install:
 - chmod +x gradlew

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

notifications:
  email: false